# ************* server *************
server:
  port: 8088
  # 设置请求和响应头的最大量 超过长度不予处理
  max-http-header-size: 8192
  use-forward-headers: true

# ************* spring *************
spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化数量
      initialSize: 1
      # 最大活跃数
      maxActive: 20
      # 最大连接等待超时时间
      maxWait: 60000
      # 打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
      logSlowSql: true
  # jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# ************* log *************
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

# ************* 自定义配置 *************

